services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  db2:
    image: postgres:latest
    environment:
      POSTGRES_USER: myuser2
      POSTGRES_PASSWORD: mypassword2
      POSTGRES_DB: mydatabase2
    ports:
      - "5433:5432"
    volumes:
      - postgres_data2:/var/lib/postgresql/data

  product:
    build: ./product
    ports:
      - "5001:5001"
    environment:
      DATABASE_URL: postgresql://myuser2:mypassword2@db2:5432/mydatabase2
    depends_on:
      - db2

  users:
    build: ./users
    ports:
      - "5000:5000"
    environment:
      DATABASE_URL: postgresql://myuser:mypassword@db:5432/mydatabase
    depends_on:
      - db

  auth:
    build: ./auth
    ports:
      - "5002:5002"
    environment:
      DATABASE_URL: postgresql://myuser:mypassword@db:5432/mydatabase
    depends_on:
      - db

  db_auth:
    image: postgres:15
    environment:
      POSTGRES_USER: authuser
      POSTGRES_PASSWORD: authpass
      POSTGRES_DB: authdb
    ports:
      - "5434:5432"
    volumes:
      - postgres_data_auth:/var/lib/postgresql/data

  auth-google:
    build: ./auth-google
    ports:
      - "5003:5003"
    environment:
      DATABASE_URL: postgresql://authuser:authpass@db_auth:5432/authdb
    depends_on:
      - db_auth

volumes:
  postgres_data:
  postgres_data2:
  postgres_data_auth:
